import { Task } from '@/features/shells/domain/Task';
import { TaskRepository } from '@/features/shells/domain/TaskRepository';

/**
 * Use case for creating a new task.
 * Validates input and delegates to the repository.
 */
export class CreateTaskUseCase {
    constructor(private taskRepository: TaskRepository) { }

    /**
     * Executes the use case.
     * @param userId The user ID
     * @param title Task title
     * @param description Task description
     * @param date Task date
     * @param startTime Task start time (HH:MM format)
     * @param duration Task duration in minutes
     * @returns A promise that resolves when the task is created.
     */
    async execute(
        userId: string,
        title: string,
        description: string,
        date: Date,
        startTime: string,
        duration: number
    ): Promise<void> {
        // Validation
        if (!title || title.trim().length === 0) {
            throw new Error('Task title is required');
        }

        if (title.length > 100) {
            throw new Error('Task title must be less than 100 characters');
        }

        if (description.length > 500) {
            throw new Error('Task description must be less than 500 characters');
        }

        if (duration <= 0 || duration > 1440) {
            throw new Error('Duration must be between 1 and 1440 minutes (24 hours)');
        }

        // Validate time format (HH:MM)
        const timeRegex = /^([01]\d|2[0-3]):([0-5]\d)$/;
        if (!timeRegex.test(startTime)) {
            throw new Error('Invalid time format. Use HH:MM (24-hour format)');
        }

        if (!userId) {
            throw new Error('User ID is required to create a task');
        }

        const task: Task = {
            id: '', // Will be generated by Firestore
            title: title.trim(),
            description: description.trim(),
            date,
            startTime,
            duration,
            userId,
            createdAt: new Date(),
        };

        return this.taskRepository.createTask(task);
    }
}
