'use client';

import { useState, useCallback } from 'react';
import { CreateTaskUseCase } from '@/features/shells/application/CreateTaskUseCase';
import { taskRepository } from '@/features/shells/infrastructure';
import { Task } from '@/features/shells/domain/Task';
const createTaskUseCase = new CreateTaskUseCase(taskRepository);

export function useCreateTask() {
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const createTask = useCallback(async (
        userId: string,
        title: string,
        description: string,
        date: Date,
        startTime: string,
        duration: number,
        category: string = 'work'
    ) => {
        setLoading(true);
        setError(null);

        try {
            const newTask: Task = {
                id: '', // Generated by Firestore
                title,
                description,
                date,
                startTime,
                duration,
                userId,
                createdAt: new Date(),
                category,
                status: 'pending'
            };

            await createTaskUseCase.execute(newTask);
        } catch (err) {
            const errorMessage = err instanceof Error ? err.message : 'Failed to create task';
            setError(errorMessage);
            throw err;
        } finally {
            setLoading(false);
        }
    }, [createTaskUseCase]); // Dependency array for useCallback

    return {
        createTask,
        loading,
        error,
    };
}
